spring:
  application:
    name: Scraper-Worker

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: scraper-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual

server:
  port: ${SERVER_PORT:8081}

app:
  kafka:
    topics:
      scrape-requested: scrape.requested
      scrape-completed: scrape.completed
      scrape-failed: scrape.failed
  scrapfly:
    base-url: https://api.scrapfly.io/scrape
    api-key: REMOVED_KEY_FOR_PUBLIC_ACCESS
  scraper:
    max-attempts: 4
    page-delay-ms: 1500
    page-delay-random-ms: 1500